
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@com/header/Header"; 
import Footer from "@com/footer/Footer";
import Loader from "./loading"
const inter = Inter({ subsets: ["latin"] });
import React from "react";
import { UserProvider } from '@auth0/nextjs-auth0/client';
export const metadata = {
  title: "IEEE",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {   
  return (
    <html lang="en">
      <UserProvider>
      <body className={inter.className}>
        
        <div className="wrapper overflow-y-scroll no-scrollbar">
        
        {/* <Suspense fallback={<Loader />}> */}
          <Header />
            {children}
          <Footer />
          {/* </Suspense> */}
        </div>
      
      </body>
      </UserProvider>
    </html>
  );
}
