import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@com/header/Header"; 
import Footer from "@com/footer/Footer";
const inter = Inter({ subsets: ["latin"] });

import { UserProvider } from '@auth0/nextjs-auth0/client';
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <UserProvider>
      <body className={inter.className}>
        <div className="wrapper">
          <Header />
            {children}
          <Footer />
        </div>
      
      </body>
      </UserProvider>
    </html>
  );
}
